### ISSUE TITLE
Neither color nor B&W conversion working

### ISSUE THREAD

**Issue by Herd001** [nnnn2cat/WQV_PDB_Tools#1]
Hi,

Trying to get the images of my WQV-1 and WQV-10 watches, I have imported them to my Palm Pilot M500 running Palm OS 4.1 via the WQV apps and backup to the data to my PC, when trying to convert with your program neither the monochrome or color conversion tools seem to work

With the monochrome tool, I have put the WQVLinkDB file into the PDB, when I run convert it dumps a load of PDR files into the Work folder with no JPEGs in the Out folder.

With the color tool I've done as the Readme states but when I try to run Convert I get an error saying VCRUNTIME140D.dll was not found and ucrtbased.dll was not found, I have installed the latest version of Microsoft Visual C++ Redistributable and Python

Thanks

**Comment by nnnn2cat** [comment]
Thanks for the comment, and sorry for the trouble. Would it be possible to request the .pdb files so I can try to debug? I've only tested with my own data so far (and my watches are wqv-2 and wqv-3, so it's possible there's some difference in the formatting).

There is a 'monochrome fix' fork over here;
https://github.com/neolithicau/WQV_PDB_Tools_Monochrome-fix

I would be interested in hearing if this solves the issue for your wqv-1 data.

**Comment by Herd001** [comment]
Hi thanks for getting back to me, here are the pbd files for both monochrome and color. I tried the fix fork but still have the same issue as reported with PDR files just being dumped into the work folder.
[pdb.zip](https://github.com/user-attachments/files/17617417/pdb.zip)

**Comment by nnnn2cat** [comment]
Herd001, thanks for the help!
For the monochrome version, it looks like it was attempting to convert github settings files (.gitkeep) and failing; this is fixed, and I've confirmed that it works with your WQVLink.pdb now.

For the color version, is it possible that you're using a 32 bit computer? I had built the jpegrip middleware (source here: https://github.com/rusq/jpegrip) for 64 bit architecture originally, so I replaced the exe with a 32 bit version. This should hopefully now work on both 32 bit and 64 bit machines.

I was able to convert the images in your zip successfully, so if you're still having trouble please let me know. (Worst case scenario I can send the converted images via email.)

**Comment by Herd001** [comment]
Hi thanks for the continued efforts!

I am using a 64 bit machine, using the latest version the color photos were able to be successfully converted though output into the work folder instead of the out folder but that's fine since they actually worked!

As for the monochrome I'm oddly still encountering the same issue as before

**Comment by nnnn2cat** [comment]
Sorry, it looks like I made a dumb mistake on the last commit (wrong file extension). I updated the repository again, hopefully it should work this time...!

EDIT: It would also help if you ran convert.bat from the command line, so I could know where the problem lies.

**Comment by Herd001** [comment]
Hi, here attached is what I get when running via command line hope this helps

[PDB convert command.txt](https://github.com/user-attachments/files/17707305/PDB.convert.command.txt)

**Comment by nnnn2cat** [comment]
Herd001, thanks again for your continued help!

It looks like you don't have Python Image Library (PIL) installed.
My apologies, for some reason I thought it was included with the standard Python install.
I'll update the readme to reflect this!

If you open command prompt and type 
`pip install Pillow`
it should install the library for you. 

Source: https://stackoverflow.com/questions/8863917/importerror-no-module-named-pil

This would also explain why your color images made it to the work folder, but not the output folder. If you run this again with PIL installed, it should fix up any corruption that was in the jpegs converted by WQV_monochrome.

**Comment by Herd001** [comment]
Hi, I've installed pillow as instructed however now when running the match file via command I get the same error as in the previous provided .txt file, and no converted images for monochrome
Pillow version is 11.0.0
> pillow in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (11.0.0)

**Comment by nnnn2cat** [comment]
Do you perhaps have multiple versions of Python installed?

If you type
`pip show pillow`
And
`pip3 show pillow`

And the first command works but the second does not, you may have to type 
`pip3 install pillow` to ensure PIL is being installed to the right version.

Alternatively, you can try changing 'py -3' in the batch file to just 'python,' since it seems your default python install is 3.x anyway.

Source: https://stackoverflow.com/questions/69822301/python-pillow-or-pil-not-working-despite-pip-installation

**Comment by Herd001** [comment]
Only one installation of python on my machine, installed for this converter. 
Both commands listed work

**Comment by nnnn2cat** [comment]
Not sure what to say if the issue is still saying that it can't find PIL. I don't think I'm doing anything unusual in how I import it.

Here's some python sample code for PIL. This imports Image from PIL in the exact same way, so if you can get one to work, they both should.

https://pillow.readthedocs.io/en/stable/handbook/tutorial.html

For the meantime, if you can send the .pdb file to my email address included in readme.txt, I can at least get the images converted and send them back to you.

Sorry I couldn't be of more help.

**Comment by nnnn2cat** [comment]
Hey, just wanted to check back on this and see if you had any more updates.

**Comment by Herd001** [comment]
Hey

Yeah I still haven't gotten it to work on my PC, but works just fine on my roommates so I sort of gave up on trying...

**Comment by nnnn2cat** [comment]
Glad you were able to get it to work. Closing this for now, sorry for the trouble!
